### ISSUE TITLE
HTTP metrics do not adhere to Prometheus best practice

### ISSUE THREAD

**Issue by errordeveloper** [etf1/restify-prom-bundle#2]
I wanted to make a PR to fix this, but it looks a little non-trivial and I was wondering to hear author's take on this.

I think that two metrics this library should expose would be `http_request_duration_miliseconds` and `http_requests_total`, with an option to disable path label.

@jucrouzet @ddalmais what do you think?

**Comment by jucrouzet** [comment]
Hi @errordeveloper,
The bundle exposes `restify_path_duration` as an [Histogram](https://prometheus.io/docs/practices/histograms/), you can exclude some paths with the `exclude` option (path or regex).
Is it what you're looking at ?

**Comment by errordeveloper** [comment]
No, that wasn't exactly what I meant... but I ended-up patching epimetheus.
