### ISSUE TITLE
A metric with the name restify_status_codes has already been registered.

### ISSUE THREAD

**Issue by ariden83** [etf1/restify-prom-bundle#5]
Hello,

When I call your lib as : 

`this._server.pre(promBundle.preMiddleware(this._server));`

I've got this error :

`A metric with the name restify_status_codes has already been registered.`

Do you know how to resolve it ?

I comment in my code all healthz / metrics routes, it's change nothing..

**Comment by ariden83** [comment]
I found solution, I don't know if I'ts good..., we need to do:

`promBundle.client.register.clear();`

before 

`this._server.pre(promBundle.preMiddleware(this._server));`

..

**Comment by jucrouzet** [comment]
"A metric with the name restify_status_codes has already been registered." denotes that the pre-middleware is registered twice.

This could be : 
1) You set `this._server.pre(promBundle.preMiddleware(this._server));` twice
2) You are trying to re instantiate your server (eg: unit test).
